### ISSUE TITLE
Allow keepers to atomically perform a rebalance and arb trade

### ISSUE THREAD

**Issue by TomAFrench** [balancer-labs/balancer-core-v2#578]
We currently have two flavours of rebalancing available  (`rebalance` and `rebalanceAndSwap`) which are both targeted at the case of the pool being critically under-invested such that it needs to pay out a fee to the keeper.

In the case that the pool is over-invested such that it is running out of cash, the price for the asset manager's token will be quoted as too low relative to the market. If the keeper can identify a closed loop on Balancer to satisfy the arb then we could have something like `rebalanceAndArb` which performs this trade to buy up the cheap tokens.

However we should keep the avenue open to use sources of liquidity which are not on Balancer V2 to satisfy this arb so the keeper needs to be able to provide their own tokens. To keep this functionality on the asset manager would require either a) every asset manager is a relayer (which is a no go) or b) keepers have to approve the asset manager to take their funds before they cause a rebalance so they can be used in the swap.

We should potentially create a relayer which allows something like this

```
function rebalanceAndArb(IAssetManager assetManager, bytes32 poolId, BatchSwap swap) external {
    assetManager.rebalance(poolId);
    vault.batchSwap(swap.swaps, swap.assets, swap.funds, swap.limits, swap.deadline);
}

```

The keepers can then just reuse their approval on the vault to perform this trade without having to send tokens off to another contract first.

**Comment by nventuro** [comment]
I really like this idea!

>targeted at the case of the pool being critically under-invested such that it needs to pay out a fee to the keeper.

Note that while `rebalanceAndArb` would only make sense in a low-cash scenario, the plan is to make the fee payout happen in both high-cash and low-cash scenarios, to prevent relying on sophisticated keepers (i.e. arbers).

An issue that arises with the rebalance -> swap pattern is that the end state does not have a balanced asset manager: the swap would take post-rebalance cash from the token in question (how much depends on how out of sync the Pool token price was).

**Comment by TomAFrench** [comment]
> Note that while `rebalanceAndArb` would only make sense in a low-cash scenario, the plan is to make the fee payout happen in both high-cash and low-cash scenarios, to prevent relying on sophisticated keepers (i.e. arbers).

Ah so the plan is to have critical over-invested and under-invested thresholds rather than just under-invested? I was working on the understanding that we only have a single critical threshold.

> An issue that arises with the rebalance -> swap pattern is that the end state does not have a balanced asset manager: the swap would take post-rebalance cash from the token in question (how much depends on how out of sync the Pool token price was).

That's true but we can't really control this without forcing the keeper to trade (or not trade) away the fee against the pool in question. I think the important thing is to just ensure that the fees aren't significant relative to the width of the band of acceptable managed balances.

**Comment by nventuro** [comment]
>Ah so the plan is to have critical over-invested and under-invested thresholds rather than just under-invested? I was working on the understanding that we only have a single critical threshold.

Correct: at least initially, want to have this mechanism in both directions so that simple bots suffice. We will likely even run the initial bots ourselves (with zero fees).

**Comment by TomAFrench** [comment]
Closing as not necessary for first implementation. Can reopen if we want to explore further.
